package com.saschaw.hooked.core.designsystem.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00687C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF96E6FE)
val onPrimaryContainerLight = Color(0xFF004A59)
val secondaryLight = Color(0xFF47636C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCEECF6)
val onSecondaryContainerLight = Color(0xFF334F57)
val tertiaryLight = Color(0xFF785A10)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDA92)
val onTertiaryContainerLight = Color(0xFF5B4200)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF7FAFB)
val onBackgroundLight = Color(0xFF181C1E)
val surfaceLight = Color(0xFFF7FAFB)
val onSurfaceLight = Color(0xFF181C1E)
val surfaceVariantLight = Color(0xFFDAE4E8)
val onSurfaceVariantLight = Color(0xFF3F484C)
val outlineLight = Color(0xFF6F797C)
val outlineVariantLight = Color(0xFFBEC8CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3132)
val inverseOnSurfaceLight = Color(0xFFEEF1F3)
val inversePrimaryLight = Color(0xFF82D2EA)
val surfaceDimLight = Color(0xFFD7DADC)
val surfaceBrightLight = Color(0xFFF7FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F4F6)
val surfaceContainerLight = Color(0xFFEBEEF0)
val surfaceContainerHighLight = Color(0xFFE6E9EA)
val surfaceContainerHighestLight = Color(0xFFE0E3E4)

val primaryDark = Color(0xFFF3FCFF)
val onPrimaryDark = Color(0xFF003641)
val primaryContainerDark = Color(0xFF8BDBF3)
val onPrimaryContainerDark = Color(0xFF004350)
val secondaryDark = Color(0xFFAECBD6)
val onSecondaryDark = Color(0xFF17343C)
val secondaryContainerDark = Color(0xFF27444C)
val onSecondaryContainerDark = Color(0xFFBCD9E4)
val tertiaryDark = Color(0xFFFFFFFF)
val onTertiaryDark = Color(0xFF402D00)
val tertiaryContainerDark = Color(0xFFF8CF7B)
val onTertiaryContainerDark = Color(0xFF533B00)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101415)
val onBackgroundDark = Color(0xFFE0E3E4)
val surfaceDark = Color(0xFF101415)
val onSurfaceDark = Color(0xFFE0E3E4)
val surfaceVariantDark = Color(0xFF3F484C)
val onSurfaceVariantDark = Color(0xFFBEC8CC)
val outlineDark = Color(0xFF889296)
val outlineVariantDark = Color(0xFF3F484C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E3E4)
val inverseOnSurfaceDark = Color(0xFF2D3132)
val inversePrimaryDark = Color(0xFF00687C)
val surfaceDimDark = Color(0xFF101415)
val surfaceBrightDark = Color(0xFF363A3B)
val surfaceContainerLowestDark = Color(0xFF0B0F10)
val surfaceContainerLowDark = Color(0xFF181C1E)
val surfaceContainerDark = Color(0xFF1C2022)
val surfaceContainerHighDark = Color(0xFF272B2C)
val surfaceContainerHighestDark = Color(0xFF313537)






